services:
  db:
    image: pgvector/pgvector:pg17 # Uses PostgreSQL 17 with pgvector 0.8.0 (latest)
    container_name: ace_mail_db
    restart: always
    environment:
      POSTGRES_USER: ace_user
      POSTGRES_PASSWORD: ace_password
      POSTGRES_DB: ace_mail_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Optional: Script to initialize pgvector extension if not enabled by default
      # - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    # Remove port exposure for production (only needed for local development)
    # ports:
    #   - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ace_mail_backend
    restart: on-failure
    # Remove port exposure - will be accessed through nginx proxy
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://ace_user:ace_password@db:5432/ace_mail_db
      FLASK_ENV: development # Or production
      # Add other backend environment variables as needed

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ace_mail_frontend
    restart: on-failure
    # Remove port exposure - will be accessed through nginx proxy
    depends_on:
      - backend

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: ace_mail_nginx
    restart: always
    ports:
      - "80:80"   # Main application port
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data: