"""Add Email model

Revision ID: 119afe5a0705
Revises: 258471017e8d
Create Date: 2025-06-06 11:02:26.984602

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR


# revision identifiers, used by Alembic.
revision = '119afe5a0705'
down_revision = '258471017e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id_header', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('recipient', sa.Text(), nullable=True),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('received_date', sa.DateTime(), nullable=True),
    sa.Column('imap_uid', sa.Integer(), nullable=True),
    sa.Column('embedding', VECTOR(dim=384), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emails_imap_uid'), ['imap_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_message_id_header'), ['message_id_header'], unique=True)
        batch_op.create_index(batch_op.f('ix_emails_received_date'), ['received_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emails_received_date'))
        batch_op.drop_index(batch_op.f('ix_emails_message_id_header'))
        batch_op.drop_index(batch_op.f('ix_emails_imap_uid'))

    op.drop_table('emails')
    # ### end Alembic commands ###
