"""Add encrypted_email_password to User model

Revision ID: 258471017e8d
Revises: f6574f5e6326
Create Date: 2025-06-06 10:59:34.871731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258471017e8d'
down_revision = 'f6574f5e6326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_email_password', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('encrypted_email_password')

    # ### end Alembic commands ###
