"""Remove unique constraint from message_id_header

Revision ID: 2cdbd526db71
Revises: 63568a892701
Create Date: 2025-06-06 05:50:46.678822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cdbd526db71'
down_revision = '63568a892701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emails_message_id_header'))
        batch_op.create_index(batch_op.f('ix_emails_message_id_header'), ['message_id_header'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emails_message_id_header'))
        batch_op.create_index(batch_op.f('ix_emails_message_id_header'), ['message_id_header'], unique=True)

    # ### end Alembic commands ###
