"""Add email body fields and folder support

Revision ID: 63568a892701
Revises: 8e58cc391cf0
Create Date: 2025-06-06 15:26:46.419867

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR


# revision identifiers, used by Alembic.
revision = '63568a892701'
down_revision = '8e58cc391cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_full', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('body_html', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('body_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('folder', sa.String(length=50), nullable=True))
        batch_op.alter_column('embedding',
               existing_type=sa.NUMERIC(precision=384),
               type_=VECTOR(384),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=VECTOR(384),
               type_=sa.NUMERIC(precision=384),
               existing_nullable=True)
        batch_op.drop_column('folder')
        batch_op.drop_column('body_text')
        batch_op.drop_column('body_html')
        batch_op.drop_column('body_full')

    # ### end Alembic commands ###
