"""Add IMAP/SMTP settings to User model

Revision ID: 8e58cc391cf0
Revises: 119afe5a0705
Create Date: 2025-06-06 11:07:39.367773

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR


# revision identifiers, used by Alembic.
revision = '8e58cc391cf0'
down_revision = '119afe5a0705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=sa.NUMERIC(precision=384), # This might need to be sa.BLOB or another type if SQLite reflected it differently
               type_=VECTOR(dim=384),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_provider_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('imap_host', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('imap_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('smtp_host', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('smtp_port', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('smtp_port')
        batch_op.drop_column('smtp_host')
        batch_op.drop_column('imap_port')
        batch_op.drop_column('imap_host')
        batch_op.drop_column('email_provider_type')

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=VECTOR(dim=384),
               type_=sa.NUMERIC(precision=384), # Or sa.BLOB, matching how SQLite might see it
               existing_nullable=True)

    # ### end Alembic commands ###
