"""Add email analysis fields

Revision ID: 90d5ea77ccb5
Revises: 2cdbd526db71
Create Date: 2025-06-06 18:11:08.569204

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR


# revision identifiers, used by Alembic.
revision = '90d5ea77ccb5'
down_revision = '2cdbd526db71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('should_preserve_layout', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('should_force_left_align', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cleaned_html', sa.Text(), nullable=True))
        batch_op.alter_column('embedding',
               existing_type=sa.NUMERIC(precision=384),
               type_=VECTOR(384),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=VECTOR(384),
               type_=sa.NUMERIC(precision=384),
               existing_nullable=True)
        batch_op.drop_column('cleaned_html')
        batch_op.drop_column('should_force_left_align')
        batch_op.drop_column('should_preserve_layout')
        batch_op.drop_column('email_type')

    # ### end Alembic commands ###
