"""Initial migration with User table.

Revision ID: f6574f5e6326
Revises: 
Create Date: 2025-06-06 10:39:45.416923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6574f5e6326'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute('DROP EXTENSION IF EXISTS vector;') # Optional: consider if other tables might use it
    # ### end Alembic commands ###
